name: 'Setup Crowdin CLI'
description: 'Set up Crowdin CLI in your GitHub Actions workflow'
author: 'Ilya Gulya'
branding:
  icon: 'download'
  color: 'blue'

inputs:
  version:
    description: 'Version of Crowdin CLI to use (e.g. 3.16.0)'
    required: false
    default: 'latest'
  github_token:
    description: 'GitHub token for API access to fetch release information'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js' 
