name: Build and Release Crowdin CLI

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
  # Allow manual triggering
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: '23'

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.check-version.outputs.new_version }}
      version: ${{ steps.check-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for new Crowdin CLI version
        id: check-version
        # language=bash
        run: |
          # Get the latest release from Crowdin CLI repository
          LATEST_VERSION=$(curl -s https://api.github.com/repos/crowdin/crowdin-cli/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          echo "Latest Crowdin CLI version: $LATEST_VERSION"
          
          # For tag-based triggers, use the tag version
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            TAG_VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
            echo "Using tag version: $TAG_VERSION"
            echo "new_version=true" >> $GITHUB_OUTPUT
            echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Check if we already have a release for this version
          if curl -s -f -I "https://github.com/${{ github.repository }}/releases/tag/v$LATEST_VERSION" > /dev/null; then
            echo "Release for version $LATEST_VERSION already exists. Skipping."
            echo "new_version=false" >> $GITHUB_OUTPUT
          else
            echo "New version $LATEST_VERSION detected. Will create a release."
            echo "new_version=true" >> $GITHUB_OUTPUT
            echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          fi

  build-native:
    needs: check-for-updates
    if: ${{ needs.check-for-updates.outputs.new_version == 'true' }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            artifact: crowdin-cli-linux-amd64
          - runner: ubuntu-24.04-arm
            artifact: crowdin-cli-linux-arm64
          - runner: macos-latest
            artifact: crowdin-cli-macos-arm64
          - runner: macos-13
            artifact: crowdin-cli-macos-x86_64
    steps:
      - name: Download and Extract Crowdin CLI
        # language=bash
        run: |
          VERSION=${{ needs.check-for-updates.outputs.version }}
          # Download the zip file
          echo "Downloading Crowdin CLI zip for version ${VERSION}..."
          curl -L -o crowdin-cli.zip "https://github.com/crowdin/crowdin-cli/releases/download/${VERSION}/crowdin-cli.zip"
          unzip -j crowdin-cli.zip
                    
          # Verify the JAR file was moved successfully
          if [ ! -f crowdin-cli.jar ]; then
            echo "ZIP does not contain crowdin-cli.jar"
            exit 1
          fi
          
          echo "Successfully extracted crowdin-cli.jar"

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native image
        # language=bash
        run: |
          native-image -Os -jar crowdin-cli.jar \
            --no-fallback \
            -H:+ReportExceptionStackTraces \
            ${{ matrix.artifact }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}

  create-release:
    needs: [ check-for-updates, build-native ]
    if: ${{ needs.check-for-updates.outputs.new_version == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets
          merge-multiple: true

      - name: Generate sha256 checksums
        # language=bash
        run: |
          cd release-assets
          for file in *; do
            sha256sum $file > $file.sha256
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.check-for-updates.outputs.version }}
          name: Crowdin CLI v${{ needs.check-for-updates.outputs.version }}
          body: |
            Native executables for Crowdin CLI v${{ needs.check-for-updates.outputs.version }}
            
            These are built using GraalVM native-image for better performance and no Java dependency.
            
            Original Crowdin CLI: https://github.com/crowdin/crowdin-cli/releases/tag/v${{ needs.check-for-updates.outputs.version }}
          files: release-assets/*
          draft: false
          prerelease: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
